--- #This is a commented line
- hosts: onprem
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: testuser
  tasks:
  - name: Install httpd
    apt:
      name: httpd
      state: present
    notify:
      - startservice
  handlers:
  - name: startservice
    service:
      name: httpd
      state: restarted
