--- #This is a commented line
- hosts: onprem
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: testuser
  tasks:
  - name: Install npm
    apt:
      name: npm
      state: absent
